.\" This file is licensed under the BSD\[hy]3\[hy]Clause license.
.\" See the AUTHORS and LICENSE files for more information.
.Dd May 19, 2020
.Dt NIIVIEW
.
.Sh NAME
.Nm niiview
.Nd display a nifti file with an xterminal.
.
.Sh SYNOPSIS
.Nm
.Op Fl Fl help
.Op Fl Fl info
.Op Fl Fl loop
.Op Fl Fl dpi Ar N
.Op Fl Fl slices Ar N,N,N
.Op Fl Fl percent Ar N,N,N
.Op Fl Fl step_size Ar N
.Fa nifti_file
.
.Sh DESCRIPTION
.Nm
displays a brain image from a nifti file in an xterminal.
Its arguments are:
.Sh --help
Display the help text of niiview.
.Sh --info
Print basic information about the nifti file.
.Sh --loop
This opens the image in a loop, so that it is possible to go trough the brain with the keyboard.
.Sh --dpi
This argument changes the size of the image that gets displayed in the terminal.
.Sh --slices
Shows the brain at the koordinates x,y,z (zb niiview --show 50,50,50 image.nii ).
By default, it selects the middle slices of the image.
.Sh --percent
Instead of showing the brain at specific slices, this option shows the slices in percentages.
By default the middle slices get shown at 50,50,50.
.Sh --step_size
While in loop-mode, this option sets the number of image-slices that get changed each time a key is pressed. 
By default, the step_size is 10.
.Sh nifti_file
This argument discribes a nifti file, that can be displayed with niiview.
If called without further options, niiview displays the middle slices of the brain image and exits the program.
.
